[package]
name = "hashmap_test"
version = "0.1.0"
authors = ["Andrea Cracco <guilucand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hashmap_test"

[dependencies]
hashbrown = "0.11.2"
rand = "0.8.4"
